apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedemoapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: kubedemoapp
  template:
    metadata:
      labels:
        app: kubedemoapp
    spec:
      containers:
        - name: mycontainer
          image: sreelasya24/first:latest
          ports:
            - containerPort: 5000
