apiVersion: v1
kind: Service
metadata:
  name: kubedemoapp-service
spec:
  selector:
    app: kubedemoapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30058
